version: "3.4"

volumes:
  app-data:
    driver: local

networks:
  app-network:
    driver: bridge

services:
  fpm:
    image: gregorip02/laravel-mongo-app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "9000"
    networks:
      - "app-network"
    volumes:
      - $PWD:/opt/app:rw
    env_file: .env

  nginx:
    image: gregorip02/nginx-php
    restart: unless-stopped
    environment:
      NGINX_HOST: "localhost"
      NGINX_ROOT: "/opt/app/public"
      NGINX_FASTCGI: "fpm:9000"
    volumes:
     - $PWD:/opt/app:ro
    ports:
      - "8080:80"
    networks:
      - "app-network"
    depends_on:
      - "fpm"

  mongo:
    image: mongo:3.6-xenial
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_DATABASE}
    networks:
      - "app-network"
    volumes:
      - app-data:/data/db
