version: "3.4"

volumes:
  app-data:
    driver: local

networks:
  app-network:
    driver: bridge

services:
  app:
    image: gregorip02/laravel-fpm:mongo
    restart: unless-stopped
    env_file: .env
    volumes:
      - $PWD:/opt/app
      - $PWD/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - "app-network"

  mongo:
    image: mongo:3.6-xenial
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_DATABASE}
    networks:
      - "app-network"
    volumes:
      - app-data:/data/db
