version: "3.4"

volumes:
  mongo-data:
    driver: local

networks:
  nginx-network:
    driver: bridge
  mongo-network:
    driver: bridge

services:
  fpm:
    image: gregorip02/laravel-fpm:mongo
    working_dir: /var/www/app
    container_name: fpm
    restart: on-failure
    volumes:
      - $PWD:/var/www/app
    expose:
      - "9000"
    networks:
      - "nginx-network"
      - "mongo-network"

  mongo:
    image: mongo:3.6-xenial
    container_name: mongo
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_DATABASE}
    networks:
      - "mongo-network"
    volumes:
      - mongo-data:/data/db

  # If you want use MySQL instead.
  # Remember to change the DB_HOST with the service name.
  # mysql:
  #   image: mysql:5.7
  #   container_name: mysql
  #   restart: on-failure
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #   networks:
  #     - "mysql-network"
  #   environment:
  #     MYSQL_USER: ${DB_USERNAME}
  #     MYSQL_DATABASE: ${DB_DATABASE}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_RANDOM_ROOT_PASSWORD: "yes"

  www:
    image: nginx:1.17-alpine
    working_dir: /var/www/app
    container_name: nginx
    restart: on-failure
    volumes:
      - $PWD/default.conf:/etc/nginx/conf.d/default.conf
      # Mount public laravel path only
      # in the nginx web server.
      - $PWD/public:/var/www/app/public
    networks:
      - "nginx-network"
    ports:
      - "8080:80"
